SYSTEM:
    DEVICE: "cuda:0"
    NUM_WORKERS: 4
MODEL:
    BACKBONE: "resnet50" 
    MODEL: "delg_global"
    MODEL_DIR: "models"
DATASET:
    TRAIN_DATA_DIR: "train"
    TEST_DATA_DIR: "test"
    TRAIN_CSV: "train_sub_class.csv"
    IMAGE_SIZE: 256
TRAIN:
    BATCH_SIZE: 16
    EPOCHS: 30
    FREEZE_BACKBONE: False
    OPTIM:
        OPTIMIZER: "sgd"
        BASE_LR: 0.005
        SGD_MOMENTUM: 0.9
        ADAM_BETAS: (0.9, 0.95)
        LR_DECAY_RATE: 0.8
        LR_DECAY_FREQUENCY: 2
EVAL:
    MODEL_PATH: "models/resnet50_delg_global.pth" # For test.py
    BATCH_SIZE: 4
    SAVE_FREQUENCY: 25
    SAVE_DIR: "./output"

